# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'2.3.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:

# Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)
# Create an integer null vector
int_null_vector = np.zeros(10, dtype=int)
print(int_null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
# Create a sample NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64) 
# Get the total memory size in bytes
memory_size_bytes = arr.nbytes
print(f"The memory size of the array is: {memory_size_bytes} bytes")


# Calculate memory size manually
memory_size_manual = arr.size * arr.itemsize

print(f"Total elements: {arr.size}")
print(f"Size of each element: {arr.itemsize} bytes")
print(f"The manually calculated memory size is: {memory_size_manual} bytes")

The memory size of the array is: 48 bytes
Total elements: 6
Size of each element: 8 bytes
The manually calculated memory size is: 48 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
#np.add.__doc__
#np.info(np.add)
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
# Create a null vector of size 10
null_vector = np.zeros(10,dtype=np.int64)
# Set the fifth value (which is at index 4) to 1
null_vector[4] = 1

# Print the resulting vector
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
# Create a sample vector
vector = np.array([1, 2, 3, 4, 5])
vector
# Reverse the vector using slicing
reversed_vector = vector[::-1]
# Print the original and reversed vectors
print(f"Original vector: {vector}")
print(f"Reversed vector: {reversed_vector}")

Original vector: [1 2 3 4 5]
Reversed vector: [5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
arr = np.array([1, 2, 0, 0, 4, 0])
# Find the indices of non-zero elements
nonzero_indices = np.nonzero(arr)
# The result is a tuple, so we can access the array of indices using [0]
indices_array = nonzero_indices[0]

print(f"The array of indices is: {indices_array}")

The array of indices is: [0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
# Create a 3x3x3 array with random floating-point values between 0.0 and 1.0
random_array_3d = np.random.random((3, 3, 3))

# Print the resulting array
print(random_array_3d)

[[[0.88456539 0.37894842 0.85026218]
  [0.4415271  0.50444066 0.74270719]
  [0.0491025  0.56902196 0.18999979]]

 [[0.40547279 0.87488954 0.11183449]
  [0.24354043 0.1199977  0.45652307]
  [0.28115778 0.46135366 0.5450638 ]]

 [[0.18950171 0.84100743 0.72343675]
  [0.26070195 0.48865914 0.96649176]
  [0.20122128 0.50610629 0.69936333]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
# Create a 10x10 array with random float values between 0 and 1
# np.random.random takes the shape as a tuple argument (10, 10)
random_array = np.random.random((10, 10))

# Print the array to verify its contents (optional)
print("The 10x10 random array:")
print(random_array)
print("-" * 40)

# Find the minimum value in the array
# The .min() method can be called directly on the NumPy array object
min_value = random_array.min()

# Find the maximum value in the array
# The .max() method can also be called directly on the NumPy array object
max_value = random_array.max()

# Print the minimum and maximum values
print(f"Minimum value in the array: {min_value}")
print(f"Maximum value in the array: {max_value}")

The 10x10 random array:
[[0.26269326 0.93816862 0.52118459 0.55133393 0.69269439 0.97440353
  0.86584462 0.5134522  0.15991562 0.24996288]
 [0.89023765 0.21827834 0.58969266 0.85100297 0.94727062 0.75486473
  0.3143837  0.85318821 0.01747296 0.95664962]
 [0.47401872 0.0627306  0.52218882 0.57440933 0.16956695 0.26012623
  0.3460198  0.34546882 0.83983545 0.8170218 ]
 [0.31062182 0.6550631  0.74817204 0.88686063 0.01547269 0.53815934
  0.64155316 0.99839042 0.44372522 0.34057156]
 [0.81171352 0.07963748 0.97645275 0.73844953 0.33030052 0.31567999
  0.54394786 0.20124619 0.3076254  0.86564986]
 [0.43355842 0.8197651  0.26582274 0.61083675 0.71085216 0.45097807
  0.78593131 0.34513931 0.21375917 0.56015553]
 [0.3743759  0.7790774  0.2198186  0.27139901 0.58863823 0.62618252
  0.20470669 0.25291985 0.21425722 0.17165142]
 [0.1979095  0.74719813 0.08570525 0.53981221 0.75276771 0.64494592
  0.24670258 0.10094645 0.59445754 0.06639031]
 [0.63014965 0.8738666  0.62888704 0.69008123 0.60007228

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
# Create a random vector of size 30 with values from a uniform distribution over [0, 1)
random_vector = np.random.rand(30)

# Calculate the mean value of the vector
mean_value = random_vector.mean()

# Print the vector (optional) and its mean
print("The random vector of size 30 is:\n", random_vector)
print("\nThe mean value of the vector is:", mean_value)

The random vector of size 30 is:
 [0.53835473 0.82462288 0.3422581  0.4724292  0.21835941 0.28669066
 0.0423743  0.27946817 0.11604046 0.08315661 0.81760384 0.60652826
 0.95008737 0.96151725 0.51659725 0.00442268 0.96849866 0.4090991
 0.04660787 0.97497841 0.26471151 0.65972011 0.46566198 0.92462113
 0.48561187 0.88017932 0.70378345 0.42834768 0.85220004 0.60639418]

The mean value of the vector is: 0.5243642154469994


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)