Project 1 — Stock Market Analysis using NumPy
Problem Statement

A financial analyst wants to analyze stock prices for a company over multiple days and calculate:

    Daily price changes
    
    Average price
    
    Maximum & minimum price
    
    Best day to buy and sell
    
    Moving average

Concepts Covered

    NumPy arrays
    
    Statistical operations
    
    Array slicing
    
    Aggregation functions

Dataset
    Daily stock prices (10 days)

In [1]:
import numpy as np

#Stock Prices for 10 days
stockPrices=[120, 125, 123, 130, 128, 135, 140, 138, 142, 145]
prices=np.array(stockPrices)
print("Stock Prices:", prices)

Stock Prices: [120 125 123 130 128 135 140 138 142 145]


In [2]:
# Average price
avg_price = np.mean(prices)
print("Average Price: ",avg_price)

Average Price:  132.6


In [3]:
# Maximum and Minimum price
print("Max Price:", np.max(prices))
print("Min Price:", np.min(prices))

Max Price: 145
Min Price: 120


In [4]:
# Daily price change
daily_change = np.diff(prices)
print("Daily Change:", daily_change)

Daily Change: [ 5 -2  7 -2  7  5 -2  4  3]


In [5]:
# Best day to buy
buy_day = np.argmin(prices) #returns the index (position) of the minimum value in a NumPy array along a specified axis. 
print("Best Day to Buy:", buy_day)

Best Day to Buy: 0


In [6]:
# Best day to sell
sell_day = np.argmax(prices)
print("Best Day to Sell:", sell_day)

Best Day to Sell: 9


In [11]:
'''
The numpy.convolve function in Python performs a discrete, linear convolution of two one-dimensional arrays (sequences),
which is a common operation in signal processing and data analysis. 
It combines two sequences to create a third sequence representing their interaction.
'''
# Moving Average (3 days)
onesArr=np.ones(3)/3
print(onesArr)
moving_avg = np.convolve(prices, np.ones(3)/3, mode='valid') 
print("3 Day Moving Average:", moving_avg)

[0.33333333 0.33333333 0.33333333]
3 Day Moving Average: [122.66666667 126.         127.         131.         134.33333333
 137.66666667 140.         141.66666667]


FinTech Project: Fraud Detection System using NumPy
1. Problem Statement

A financial institution wants to detect suspicious transactions in customer payment data.

Fraud transactions typically have:

    Extremely high amounts
    Unusual transaction frequency
    Transactions occurring far from normal behavior

We will use NumPy to analyze transaction patterns and detect anomalies.
2. Learning Objectives

This project teaches:

    NumPy array manipulation
    Statistical analysis
    Outlier detection
    Feature engineering
    Fraud detection logic
3. Dataset Structure

We simulate transaction data with columns:

Column	           Description
transaction_id	Unique transaction
user_id	        Customer ID
amount	        Transaction amount
location	    Location code
hour	        Time of transaction

Example dataset:
TransactionID UserID Amount Location Hour
1001          1      1200     10      9
1002          2      150      10      11
1003          3      4500     25      3

4. Fraud Detection Strategy

We detect fraud using:

Rule 1
Transaction amount greater than mean + 2 × standard deviation
Rule 2
Transaction happens at unusual time (midnight hours)
Rule 3
Location different from typical location


In [15]:
#Simulated Transaction data
import numpy as np

# Transaction dataset
transaction_id = np.arange(1001,1011) #1001,1002,1003,1004,1005,1006,1007,1008,1009,1010

user_id = np.array([1,2,3,4,5,1,2,3,4,5])

amount = np.array([200,150,300,5000,250,180,7000,220,260,120])

location = np.array([10,10,11,25,10,10,10,11,10,10])

hour = np.array([9,10,11,2,14,16,3,13,17,20])


In [16]:
#Combine Dataset into Matrix
data = np.column_stack((transaction_id,user_id,amount,location,hour))

print("Transaction Dataset")

print(data)

Transaction Dataset
[[1001    1  200   10    9]
 [1002    2  150   10   10]
 [1003    3  300   11   11]
 [1004    4 5000   25    2]
 [1005    5  250   10   14]
 [1006    1  180   10   16]
 [1007    2 7000   10    3]
 [1008    3  220   11   13]
 [1009    4  260   10   17]
 [1010    5  120   10   20]]


In [22]:
#Statistical Analysis
avg_amount = np.mean(amount)
std_amount = np.std(amount)

print("Average Transaction:",avg_amount)
print("Standard Deviation:",std_amount)

#Detect High Amount Transactions
'''
Fraud if:

amount > mean + 2*std
'''
threshold = avg_amount + 2*std_amount
print(threshold)
fraud_amount = np.where(amount > threshold)

print("High Amount Fraud Index:",fraud_amount)

Average Transaction: 1368.0
Standard Deviation: 2359.3126117579245
6086.625223515849
High Amount Fraud Index: (array([6]),)


In [20]:
#Detect Suspicious Time Transactions
'''
Fraud if:
transaction hour < 5
'''
fraud_time = np.where(hour < 5)

print("Suspicious Time Transactions:",fraud_time)

Suspicious Time Transactions: (array([3, 6]),)


In [21]:
#Detect Unusual Locations
#Normal location = 10
fraud_location = np.where(location != 10)

print("Unusual Location Transactions:",fraud_location)

Unusual Location Transactions: (array([2, 3, 7]),)


In [25]:
#Combine All Fraud Signals
print(np.concatenate((fraud_amount[0],
                    fraud_time[0],
                    fraud_location[0])))
fraud_indices = np.unique(
    np.concatenate((fraud_amount[0],
                    fraud_time[0],
                    fraud_location[0]))
)

print("Fraud Transactions Index:",fraud_indices)

[6 3 6 2 3 7]
Fraud Transactions Index: [2 3 6 7]


In [26]:
#Extract Fraud Transactions
fraud_transactions = data[fraud_indices]

print("Detected Fraud Transactions")

print(fraud_transactions)

Detected Fraud Transactions
[[1003    3  300   11   11]
 [1004    4 5000   25    2]
 [1007    2 7000   10    3]
 [1008    3  220   11   13]]


In [27]:
#Fraud Score Calculation
#We assign risk score.
'''
| Score | Risk        |
| ----- | ----------- |
| 0     | Safe        |
| 1     | Low Risk    |
| 2     | Medium Risk |
| 3+    | High Fraud  |
'''
risk_score = np.zeros(len(amount))

risk_score += (amount > threshold)*2
risk_score += (hour < 5)*1
risk_score += (location != 10)*1

print("Risk Score:",risk_score)


Risk Score: [0. 0. 1. 2. 0. 0. 3. 1. 0. 0.]


In [28]:
#High Risk Transactions
high_risk = np.where(risk_score >= 2)

print("High Risk Transactions")

print(data[high_risk])

High Risk Transactions
[[1004    4 5000   25    2]
 [1007    2 7000   10    3]]
