
NumPy, a Python library used in data science and big data. 
NumPy provides a framework to express data in the form of arrays, 
and is the fundamental building block for several other Python libraries. 

You will learn how to create NumPy arrays and perform basic mathematical operations on them.
Next you will see how to modify, index, slice, and reshape the arrays; and examine the 
NumPy library's universal array functions that operate on an element-by-element basis.
Also will learn how to iterate various options through NumPy arrays. 


What is NumPy?
NumPy (Numerical Python) is the core Python library for scientific computing and numerical operations.
It provides:
Fast multidimensional arrays
Mathematical functions
Linear algebra operations
Random number generation
Matrix operations
NumPy is written in C, which makes it much faster than Python lists.

Why NumPy Instead of Python Lists?
| Feature                 | Python List | NumPy Array |
| ----------------------- | ----------- | ----------- |
| Speed                   | Slow        | Very Fast   |
| Memory                  | High        | Efficient   |
| Mathematical Operations | Difficult   | Very Easy   |
| Multi-dimensional       | Limited     | Built-in    |



Applications of NumPy
1 Machine Learning
Libraries like:
    TensorFlow
    Scikit-learn
    PyTorch
use NumPy internally.
Example:
    Vector operations
    Matrix multiplication
    Gradient calculations
2 Data Science
Used with:
    Pandas
    Matplotlib
    SciPy
Example:
    data analysis
    data transformation
    statistical operations
3 Image Processing
Images are stored as matrix of pixels.
Example:
    Image = 3D Array
    (height × width × color channel)

4 Financial Analysis
Example:
    portfolio calculations
    stock price analysis
    risk modelling
5 Scientific Computing
Used in
    Physics
    Engineering
    Weather prediction

In [4]:
#Install NumPy and Create Basic Arrays
!pip install numpy

In [16]:
#Creating Basic NumPy Array
#Conventionaly imported as np
import numpy as np
listOfNumbers=[10,20,30,40,50]
arr = np.array(listOfNumbers)
print(arr)
print(type(arr))
#Array Dimension
print(arr.ndim)

[10 20 30 40 50]
<class 'numpy.ndarray'>
1


In [11]:
tupleOfNumbers=(10,20,30,40,50)
arr = np.array(tupleOfNumbers)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [12]:
setOfNumbers=(10,20,30,40,50)
arr = np.array(setOfNumbers)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [14]:
'''
        [[1,2,3],
        [4,5,6]]
'''
#Creating 2D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [15]:
#Array Dimension
print(arr.ndim)

2


In [17]:
#Create Specialized NumPy Arrays
#NumPy provides built-in array generators.

#Zeros Array
#Creates array filled with zeros.
import numpy as np
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
#Ones Array
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#Identity Matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#Range Array
#arange() - it takes two arguments in below example first argument is a starting number and 2nd one is end number excluding
arr=np.arange(1,10) 
print(arr)
arr=np.arange(1,20,3) #In this example 3rd argument is a step value
print(arr)

[1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13 16 19]


In [24]:
#Linspace
#Creates evenly spaced numbers.
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [26]:
#Random Array
arr = np.random.rand(3,3)
print(arr)

[[0.28366155 0.04109853 0.47688443]
 [0.00924022 0.74464293 0.56338963]
 [0.64447809 0.47403227 0.70603309]]


In [30]:
'''
Describe Array Shapes and Sizes
Shape of Array
Shape shows
    rows × columns
'''
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
print(arr.shape)
#Size of Array
print(arr.size)
#Data type
print(arr.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
6
int64


In [34]:
'''
    Mathematical Operations on Arrays

NumPy supports vectorized operations.
'''
#Addition
import numpy as np

a = np.array([10,20,30])
b = np.array([1,2,3])
c = a + b

print(c)
#Subtraction
print(a-b)
#Multiplication
print(a*b)
#Division
print(a/b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [37]:
#Matrix Multiplication
import numpy as np

a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(a)
print(b)
print('*******************')
print(a*b)
print('*******************')
result = np.dot(a,b)
print(result)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
*******************
[[ 5 12]
 [21 32]]
*******************
[[19 22]
 [43 50]]


In [38]:
import numpy as np

# Generate a 3x2 2D array with random floats between 0 and 1
# arr1 has 2 columns
arr1 = np.random.rand(3, 2)
print(f"Array 1 shape: {arr1.shape}")

# Generate a 2x4 2D array with random floats between 0 and 1
# arr2 has 2 rows
arr2 = np.random.rand(2, 4)
print(f"Array 2 shape: {arr2.shape}")

# Perform the dot product (matrix multiplication)
# The result will be a 3x4 array
dot_product_result = np.dot(arr1, arr2)
print(f"Dot product result shape: {dot_product_result.shape}")
print("Dot product result array:\n", dot_product_result)


Array 1 shape: (3, 2)
Array 2 shape: (2, 4)
Dot product result shape: (3, 4)
Dot product result array:
 [[0.43346027 0.09420209 0.3804658  0.29902572]
 [0.42867609 0.07193153 0.36118261 0.28052328]
 [0.64870704 0.5460198  0.85716572 0.73753781]]


In [40]:
'''
Key Compatibility Rule
For matrix multiplication (which is what numpy.dot() performs with 2D arrays), the inner dimensions must match: 
If arr1 has shape (n, k) and arr2 has shape (k, m), the operation is valid.
The resulting array will have the shape (n, m).
If the inner dimensions (k in the example above) do not match, NumPy will raise a ValueError. 
'''
# Using the @ operator (preferred for matrix multiplication) -(Python 3.5+ preferred)
matrix_product_result = arr1 @ arr2
matrix_product_result

array([[0.43346027, 0.09420209, 0.3804658 , 0.29902572],
       [0.42867609, 0.07193153, 0.36118261, 0.28052328],
       [0.64870704, 0.5460198 , 0.85716572, 0.73753781]])

In [47]:
'''
Functions that Apply to Each Element
NumPy applies functions element-wise.
'''
import numpy as np

arr = np.array([1,2,3,4])
print(np.square(arr)) #Square of each element
print(np.sqrt(arr)) #Square Root 
print(np.exp(arr)) #Exponential of each element of an array
print(np.log(arr)) # Natural logarithm (base e)
print(np.log10(arr)) ## Base 10 logarithm
print(np.log2(arr))# Base 2 logarithm

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[0.         0.30103    0.47712125 0.60205999]
[0.        1.        1.5849625 2.       ]


In [50]:
'''
Retrieve Specific Parts of an Array
This is called Indexing and Slicing.
'''
import numpy as np
#index---------> 0 1  2   3
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[2])
print("*************************")
#2D Array
arr = np.array([[10,20,30],
                [40,50,60]])
'''
         Col   Col   Col
          0    1      2
         (0,0) (0,1)  (0,2)
row 0    10    20    30

         (1,0) (1,1)  (1,2)  
row 1    40    50    60
'''
print(arr[1,1])

10
30
*************************
50


In [54]:
#Row selection
print(arr[1])
#Column Selection
print(arr[:,1])
print('****************************')
#Slicing
print(arr[0:2,1:3])

[40 50 60]
[20 50]
****************************
[[20 30]
 [50 60]]


In [61]:
#Iterating Over Arrays
#Iterating 1D Array
import numpy as np

arr = np.array([10,20,30])

for x in arr:
    print(x)

for index,value in enumerate(arr):
    print(index," index contains element whose value is ",value)





10
20
30
0  index contains element whose value is  10
1  index contains element whose value is  20
2  index contains element whose value is  30


In [62]:
#2d array
arr_2d = np.array([[1,2,3],[3,4,5]])

for row in arr_2d:
    print(row)

for indices, value in np.ndenumerate(arr_2d):
    print(f"Indices {indices}: Value {value}")

'''
Key Differences
enumerate(): Provides a single, flat integer index, regardless of the array's dimensions.
numpy.ndenumerate(): Provides a tuple of indices corresponding to the element's exact position in a 
multidimensional array (e.g., (row, column) for a 2D array).
'''

[1 2 3]
[3 4 5]
Indices (0, 0): Value 1
Indices (0, 1): Value 2
Indices (0, 2): Value 3
Indices (1, 0): Value 3
Indices (1, 1): Value 4
Indices (1, 2): Value 5


"\nKey Differences\nenumerate(): Provides a single, flat integer index, regardless of the array's dimensions.\nnumpy.ndenumerate(): Provides a tuple of indices corresponding to the element's exact position in a \nmultidimensional array (e.g., (row, column) for a 2D array).\n"

In [66]:
#Iterating Each Element
'''
np.nditer in Python is a multidimensional iterator designed to loop through elements of arrays with 
any number of dimensions, including 2D arrays.
The main purpose of np.nditer is to provide a consistent and efficient way to iterate over every scalar element of
an array using a single for loop, which removes the need for writing nested loops for multi-dimensional arrays.
'''
import numpy as np

arr = np.array([10,20,30])

for x in np.nditer(arr):
    print(x)


print("*********************************************")
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr_2d):
    print(x)

10
20
30
*********************************************
1
2
3
4
5
6
